apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: test-app
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: test-app
  sessionAffinity: None
  type: ClusterIP